services:
  postgres:
    image: 'postgres:latest'
    container_name: SpringCommercePostgres
    restart: always
    environment:
      - 'POSTGRES_DB=springcommerce'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=abc123'
    ports:
      - '5432:5432'
    volumes:
        - 'postgres:/var/lib/postgresql/data'
volumes:
  postgres: