package vn.com.ecommerce.springcommerce;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import vn.com.ecommerce.springcommerce.domain.Account;
import vn.com.ecommerce.springcommerce.domain.Category;
import vn.com.ecommerce.springcommerce.domain.Product;
import vn.com.ecommerce.springcommerce.service.AccountService;
import vn.com.ecommerce.springcommerce.service.CategoryService;
import vn.com.ecommerce.springcommerce.service.ProductService;

import javax.management.MBeanServer;
import javax.management.ObjectName;
import java.awt.*;
import java.lang.management.ManagementFactory;

@SpringBootApplication
public class SpringcommerceApplication implements CommandLineRunner {
    @Autowired
    ProductService productService;
    @Autowired
    CategoryService categoryService;
    @Autowired
    AccountService accountService;
    public static void main(String[] args) {
            MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();

            try {
                    ObjectName mbeanName = new ObjectName("org.springframework.boot:type=Admin,name=SpringApplication");
                    if (mbs.isRegistered(mbeanName)) {
                            mbs.unregisterMBean(mbeanName);
                    }
            } catch (Exception e) {
                    e.printStackTrace();
            }


        SpringApplication.run(SpringcommerceApplication.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
            Account account = new Account();
            account.setFullname("User");
            account.setEmail("a@a.com");
            account.setPhone("0312345689");
            account.setPassword("1");
            accountService.register(account);
            Category cate_lap = new Category("Laptop");
            Category cate_phone = new Category("Smartphone");
            Category cate_acces = new Category("Accessories");
            categoryService.addCategory(cate_lap);
            categoryService.addCategory(cate_phone);
            categoryService.addCategory(cate_acces);
            /*-----------------------------------*\
              Initialize 66 products to database
            \*-----------------------------------*/
            // Laptop
            productService.addProduct(new Product("Laptop Apple MacBook Air 13 inch M2 2022 8-core CPU", 1119.9, "Silver","Apple", cate_lap, 5, "The MacBook Air is a line of laptop computers developed and manufactured by Apple Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Laptop Apple MacBook Pro 13 inch M2 2022 10-core CPU Silver", 1299.9, "Black", "Apple", cate_lap, 3, "The MacBook Pro is a line of Macintosh portable computers introduced in January 2006, by Apple Inc. It is the higher-end model of the MacBook family, sitting above the consumer-focused MacBook Air, and is sold with 13- and 16-inch screens."));
            productService.addProduct(new Product("Laptop MacBook Pro 16 inch M2 Pro 2023 12-core CPU", 2599.9, "Silver","Apple", cate_lap, 3, "The MacBook Pro is a line of Macintosh portable computers introduced in January 2006, by Apple Inc. It is the higher-end model of the MacBook family, sitting above the consumer-focused MacBook Air, and is sold with 13- and 16-inch screens."));
            productService.addProduct(new Product("Laptop Asus Vivobook 14X OLED K3405VC i5 13500H (KM006W)", 1031.69, "Silver","Asus", cate_lap, 3, "The Asus Vivobook 14X OLED K3405VC i5 13500H (KM006W) is a line of laptop computers developed and manufactured by Asus Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Asus Vivobook 14X OLED K3405VC i5 13500H (KM006W) is a line of laptop computers developed and manufactured by Asus Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. It ís equipped with 11th Gen Intel Core i5-13500H processor, 8GB RAM, 512GB SSD, 14 inch 2.8K OLED display, and RTX 3050 4GB Graphics."));
            productService.addProduct(new Product("Laptop Asus Zenbook 14 Flip OLED UP3404VA i7 1360P", 1239.49, "Black", "Asus", cate_lap, 3, "The Asus Zenbook 14 Flip OLED UP3404VA i7 1360P is a line of laptop computers developed and manufactured by Asus Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Asus Zenbook 14 Flip OLED UP3404VA i7 1360P is a line of laptop computers developed and manufactured by Asus Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Laptop Asus TUF Gaming F15 FX507VV4 i9 13900H", 1539.29, "Black", "Asus", cate_lap, 3, "The Asus TUF Gaming F15 FX507VV4 i9 13900H is a line of laptop computers developed and manufactured by Asus Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Asus TUF Gaming F15 FX507VV4 i9 13900H is a line of laptop computers developed and manufactured by Asus Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Laptop Dell Inspiron 14 5430 i5 1340P", 1199.59, "Silver", "Dell", cate_lap, 5, "The Dell Inspiron 14 5430 i5 1340P is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Dell Inspiron 14 5430 i5 1340P is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Laptop Dell Gaming G15 5530 i7 13650HX", 1659.9, "Black", "Dell", cate_lap, 3, "The Dell Gaming G15 5530 i7 13650HX is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Dell Gaming G15 5530 i7 13650HX is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Laptop Dell XPS 13 9310 i7 1165G7", 1799.9, "Silver", "Dell", cate_lap, 5, "The Dell XPS 13 9310 i7 1165G7 is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Dell XPS 13 9310 i7 1165G7 is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Dell Inspiron 14 5430 i7 1360P (71015633)", 1279.26, "Silver", "Dell", cate_lap, 5, "The Dell Inspiron 14 5430 i7 1360P (71015633) is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Dell Inspiron 14 5430 i7 1360P (71015633) is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Dell XPS 13 Plus 9320 i5 1340P (71013325)", 2125.49, "Silver","Dell", cate_lap, 3, "The Dell XPS 13 Plus 9320 i5 1340P (71013325) is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Dell XPS 13 Plus 9320 i5 1340P (71013325) is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Dell XPS 15 9530 i7 13700H (71015716)", 2889.19, "Black","Dell", cate_lap, 5, "The Dell XPS 15 9530 i7 13700H (71015716) is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Dell XPS 15 9530 i7 13700H (71015716) is a line of laptop computers developed and manufactured by Dell Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("HP EliteBook 630 G9 i7 1255U (6M146PA)", 1056.96, "Silver","HP", cate_lap, 5, "The HP EliteBook 630 G9 i7 1255U (6M146PA) is a line of laptop computers developed and manufactured by HP Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The HP EliteBook 630 G9 i7 1255U (6M146PA) is a line of laptop computers developed and manufactured by HP Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Laptop HP Envy X360 13 bf0090TU i7 (76B13PA)", 1068.9, "Black","HP", cate_lap, 5, "The HP EliteBook 840 G8 i7 1255U (6M146PA) is a line of laptop computers developed and manufactured by HP Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The HP EliteBook 840 G8 i7 1255U (6M146PA) is a line of laptop computers developed and manufactured by HP Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Laptop HP Gaming VICTUS 16 r0128TX i5 13450HX (8C5N3PA)", 1158.9, "Black","HP", cate_lap, 5, "The HP EliteBook 840 G8 i7 1255U (6M146PA) is a line of laptop computers developed and manufactured by HP Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The HP EliteBook 840 G8 i7 1255U (6M146PA) is a line of laptop computers developed and manufactured by HP Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("HP Elitebook X360 1040 G9 i7 1255U (6Z982PA)", 1630.0, "Silver", "HP", cate_lap, 5, "The HP EliteBook 840 G8 i7 1255U (6M146PA) is a line of laptop computers developed and manufactured by HP Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The HP EliteBook 840 G8 i7 1255U (6M146PA) is a line of laptop computers developed and manufactured by HP Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("HP Omen 16 n0085AX R9 6900HX (7C144PA)", 2158.39, "Black","HP", cate_lap, 5, "The HP EliteBook 840 G8 i7 1255U (6M146PA) is a line of laptop computers developed and manufactured by HP Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The HP EliteBook 840 G8 i7 1255U (6M146PA) is a line of laptop computers developed and manufactured by HP Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Laptop Asus Zenbook 14 OLED UX3402VA i5 (KM085W)", 990.3, "Black","Asus", cate_lap, 5, "The Asus Zenbook 14 OLED UX3402VA i5 (KM085W) is a line of laptop computers developed and manufactured by Asus Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Asus Zenbook 14 OLED UX3402VA i5 (KM085W) is a line of laptop computers developed and manufactured by Asus Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. It ís equipped with 11th Gen Intel Core i5-1340P processor, 16GB RAM, 512GB SSD, 14 inch 2.8K OLED display, and Intel Iris Xe Graphics."));
            productService.addProduct(new Product("Lenovo Yoga 7 14IRL8 i5 1340P (82YL006AVN)", 1010.94, "Gray","Lenovo", cate_lap, 3, "The Lenovo Yoga 7 14IRL8 i5 1340P (82YL006AVN) is a line of laptop computers developed and manufactured by Lenovo Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Lenovo Yoga 7 14IRL8 i5 1340P (82YL006AVN) is a line of laptop computers developed and manufactured by Lenovo Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Lenovo Yoga Slim 7 Pro 14IAH7 i7 (82UT006CVN)", 1259.8, "White","Lenovo", cate_lap, 5, "The Lenovo Yoga Slim 7 Pro 14IAH7 i7 (82UT006CVN) is a line of laptop computers developed and manufactured by Lenovo Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Lenovo Yoga Slim 7 Pro 14IAH7 i7 (82UT006CVN) is a line of laptop computers developed and manufactured by Lenovo Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Laptop Lenovo Gaming Legion 5 16IRH8 i5 13500H (82YA00BSVN)", 1489.8, "Black","Lenovo", cate_lap, 5, "The Lenovo Gaming Legion 5 16IRH8 i5 13500H (82YA00BSVN) is a line of laptop computers developed and manufactured by Lenovo Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Lenovo Gaming Legion 5 16IRH8 i5 13500H (82YA00BSVN) is a line of laptop computers developed and manufactured by Lenovo Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. It's equipped with 11th Gen Intel Core i5-13500H processor, 16GB RAM, 512GB SSD, 16 inch WQXGA display 165Hz, and RTX 4050 6GB Graphics."));
            productService.addProduct(new Product("Lenovo Thinkpad P16s Gen 1 i7 1260P (21BT0064VN)", 1795.25, "Black","Lenovo", cate_lap, 5, "The Lenovo Thinkpad P16s Gen 1 i7 1260P (21BT0064VN) is a line of laptop computers developed and manufactured by Lenovo Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The Lenovo Thinkpad P16s Gen 1 i7 1260P (21BT0064VN) is a line of laptop computers developed and manufactured by Lenovo Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. It's equipped with 11th Gen Intel Core i7-1260P processor, 16GB RAM, 512GB SSD, 16 inch WUXGA (1920 x 1200) display, and Quadro T550 4GB Graphics."));
            productService.addProduct(new Product("LG gram 2in1 2023 i5 1340P (14T90R-G.AH55A5)", 1410.25, "Black", "LG", cate_lap, 5, "The LG gram 2in1 2023 i5 1340P (14T90R-G.AH55A5) is a line of laptop computers developed and manufactured by LG Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The LG gram 2in1 2023 i5 1340P (14T90R-G.AH55A5) is a line of laptop computers developed and manufactured by LG Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("Laptop LG gram Style 2023 i5 1340P (14Z90RS-G.AH54A5)", 1439.99, "White","LG", cate_lap, 5, "The LG gram Style 2023 i5 1340P (14Z90RS-G.AH54A5) is a line of laptop computers developed and manufactured by LG Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The LG gram Style 2023 i5 1340P (14Z90RS-G.AH54A5) is a line of laptop computers developed and manufactured by LG Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("LG gram UltraSlim 2023 i5 1340P (15Z90RT-G.AH55A5)", 1609.5, "Black", "LG", cate_lap, 3, "The LG gram UltraSlim 2023 i5 1340P (15Z90RT-G.AH55A5) is a line of laptop computers developed and manufactured by LG Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The LG gram UltraSlim 2023 i5 1340P (15Z90RT-G.AH55A5) is a line of laptop computers developed and manufactured by LG Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            productService.addProduct(new Product("LG gram 2023 i7 1360P (16Z90R-G.AH76A5)", 1742.59, "Gray", "LG", cate_lap, 5, "The LG gram 2023 i7 1360P (16Z90R-G.AH76A5) is a line of laptop computers developed and manufactured by LG Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure. The LG gram 2023 i7 1360P (16Z90R-G.AH76A5) is a line of laptop computers developed and manufactured by LG Inc. It consists of a full-size keyboard, a machined aluminum case, and, in the more modern versions, a thin light structure."));
            // Smartphone
            productService.addProduct(new Product("iPhone 13", 680.79, "Pink", "Apple", cate_phone, 5, "The iPhone 13 is a line of smartphones designed, developed, marketed, and sold by Apple Inc. It is the fourteenth generation of the iPhone, succeeding the iPhone 12 and iPhone 12 Pro models. Apple CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2021. Pre-orders began on September 17, 2021, and the devices became available on September 24, 2021."));
            productService.addProduct(new Product("iPhone 14", 789.6, "Puple", "Apple", cate_phone, 3, "The iPhone 14 is a line of smartphones designed, developed, marketed, and sold by Apple Inc. It is the fourteenth generation of the iPhone, succeeding the iPhone 13 and iPhone 13 Pro models. Apple CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2021. Pre-orders began on September 17, 2022, and the devices became available on September 24, 2022."));
            productService.addProduct(new Product("iPhone 14 Pro Max", 1139.8, "Deep Puple", "Apple", cate_phone, 5, "The iPhone 14 Pro Max is a line of smartphones designed, developed, marketed, and sold by Apple Inc. It is the fourteenth generation of the iPhone, succeeding the iPhone 13 Pro Max and iPhone 13 Pro models. Apple CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2021. Pre-orders began on September 17, 2022, and the devices became available on September 24, 2022."));
            productService.addProduct(new Product("iPhone 15 Plus", 1064.6, "Blue","Apple", cate_phone, 5, "The iPhone 15 Plus is a line of smartphones designed, developed, marketed, and sold by Apple Inc. It is the fifteenth generation of the iPhone, succeeding the iPhone 14 and iPhone 14 Pro models. Apple CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2022. Pre-orders began on September 17, 2023, and the devices became available on September 24, 2023."));
            productService.addProduct(new Product("iPhone 15 Pro Max", 1409.09, "Blue Titanium","Apple", cate_phone, 5, "The iPhone 15 Pro Max is a line of smartphones designed, developed, marketed, and sold by Apple Inc. It is the fifteenth generation of the iPhone, succeeding the iPhone 14 Pro Max and iPhone 14 Pro models. Apple CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2022. Pre-orders began on September 17, 2023, and the devices became available on September 24, 2023."));
            productService.addProduct(new Product("Samsung Galaxy S23+ 5G", 799.9, "Green", "Samsung", cate_phone, 5, "The Samsung Galaxy S23+ 5G is a line of smartphones designed, developed, marketed, and sold by Samsung Inc. It is the twenty-third generation of the Galaxy S, succeeding the Galaxy S22+ 5G and Galaxy S22 5G models. Samsung CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2022. Pre-orders began on September 17, 2023, and the devices became available on September 24, 2023."));
            productService.addProduct(new Product("Samsung Galaxy Z Flip5 5G", 825.99, "Blue", "Samsung", cate_phone, 5, "The Samsung Galaxy Z Flip5 5G is a line of smartphones designed, developed, marketed, and sold by Samsung Inc. It is the fifth generation of the Galaxy Z Flip, succeeding the Galaxy Z Flip3 5G and Galaxy Z Flip4 5G models. Samsung CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2022. Pre-orders began on September 17, 2023, and the devices became available on September 24, 2023."));
            productService.addProduct(new Product("Samsung Galaxy S23 Ultra 5G", 999.3, "Green", "Samsung", cate_phone, 5, "The Samsung Galaxy S23 Ultra 5G is a line of smartphones designed, developed, marketed, and sold by Samsung Inc. It is the twenty-third generation of the Galaxy S, succeeding the Galaxy S22 Ultra 5G and Galaxy S22+ 5G models. Samsung CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2022. Pre-orders began on September 17, 2023, and the devices became available on September 24, 2023."));
            productService.addProduct(new Product("Samsung Galaxy Z Fold5 5G", 1389.69, "Cream", "Samsung", cate_phone, 5, "The Samsung Galaxy Z Fold5 5G is a line of smartphones designed, developed, marketed, and sold by Samsung Inc. It is the fifth generation of the Galaxy Z Fold, succeeding the Galaxy Z Fold3 5G and Galaxy Z Fold4 5G models. Samsung CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2022. Pre-orders began on September 17, 2023, and the devices became available on September 24, 2023."));
            productService.addProduct(new Product("OPPO Reno8 T 5G", 370.88, "Black", "OPPO", cate_phone, 5, "The OPPO Reno8 T 5G is a line of smartphones designed, developed, marketed, and sold by OPPO Inc. It is the eighth generation of the Reno, succeeding the Reno7 T 5G and Reno7 5G models. OPPO CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2022. Pre-orders began on September 17, 2023, and the devices became available on September 24, 2023."));
            productService.addProduct(new Product("OPPO Reno10 5G", 399.49, "Blue", "OPPO", cate_phone, 8, "The OPPO Reno10 5G is a line of smartphones designed, developed, marketed, and sold by OPPO Inc. It is the tenth generation of the Reno, succeeding the Reno9 5G and Reno9 Pro 5G models. OPPO CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2022. Pre-orders began on September 17, 2023, and the devices became available on September 24, 2023."));
            productService.addProduct(new Product("OPPO Reno10 Pro 5G", 599.09, "Black", "OPPO", cate_phone, 5, "The OPPO Reno10 Pro 5G is a line of smartphones designed, developed, marketed, and sold by OPPO Inc. It is the tenth generation of the Reno, succeeding the Reno9 Pro 5G and Reno9 5G models. OPPO CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2022. Pre-orders began on September 17, 2023, and the devices became available on September 24, 2023."));
            productService.addProduct(new Product("OPPO Find N3 Flip 5G", 949.09, "Pink", "OPPO", cate_phone, 5, "The OPPO Find N3 Flip 5G is a line of smartphones designed, developed, marketed, and sold by OPPO Inc. It is the third generation of the Find N, succeeding the Find N2 Flip 5G and Find N2 5G models. OPPO CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2023. Pre-orders began on September 17, 2024, and the devices became available on September 24, 2024."));
            productService.addProduct(new Product("OPPO Find N3 5G", 1855.93, "Yellow", "OPPO", cate_phone, 5, "The OPPO Find N3 5G is a line of smartphones designed, developed, marketed, and sold by OPPO Inc. It is the third generation of the Find N, succeeding the Find N2 5G and Find N2 Flip 5G models. OPPO CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2023. Pre-orders began on September 17, 2024, and the devices became available on September 24, 2024."));
            productService.addProduct(new Product("Xiaomi Redmi Note 12 Pro 5G", 325.99, "Blue", "Xiaomi", cate_phone, 4, "The Xiaomi Redmi Note 12 Pro 5G is a line of smartphones designed, developed, marketed, and sold by Xiaomi Inc. It is the twelfth generation of the Redmi Note, succeeding the Redmi Note 11 Pro 5G and Redmi Note 11 5G models. Xiaomi CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2023. Pre-orders began on September 17, 2024, and the devices became available on September 24, 2024."));
            productService.addProduct(new Product("Xiaomi 13 Lite 5G", 399.49, "Black", "Xiaomi", cate_phone, 5, "The Xiaomi 13 Lite 5G is a line of smartphones designed, developed, marketed, and sold by Xiaomi Inc. It is the thirteenth generation of the Xiaomi, succeeding the Xiaomi 12 Lite 5G and Xiaomi 12 5G models. Xiaomi CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2023. Pre-orders began on September 17, 2024, and the devices became available on September 24, 2024."));
            productService.addProduct(new Product("Xiaomi 13T 5G", 499.09, "Blue", "Xiaomi", cate_phone, 5, "The Xiaomi 13T 5G is a line of smartphones designed, developed, marketed, and sold by Xiaomi Inc. It is the thirteenth generation of the Xiaomi, succeeding the Xiaomi 12T 5G and Xiaomi 12T Pro 5G models. Xiaomi CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2023. Pre-orders began on September 17, 2024, and the devices became available on September 24, 2024."));
            productService.addProduct(new Product("Xiaomi 13T Pro 5G", 599.09, "Green", "Xiaomi", cate_phone, 5, "The Xiaomi 13T Pro 5G is a line of smartphones designed, developed, marketed, and sold by Xiaomi Inc. It is the thirteenth generation of the Xiaomi, succeeding the Xiaomi 12T Pro 5G and Xiaomi 12T 5G models. Xiaomi CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2023. Pre-orders began on September 17, 2024, and the devices became available on September 24, 2024."));
            productService.addProduct(new Product("OPPO Realme 11 Pro+ 5G", 559.49, "White", "OPPO", cate_phone, 5, "The Oppo Realme 11 Pro+ 5G is a line of smartphones designed, developed, marketed, and sold by Oppo Inc. It is the eleventh generation of the Realme, succeeding the Realme 10 Pro+ 5G and Realme 10 5G models. Realme is a sub-brand of Oppo which known for its budget phones and super-fast charging."));
            // Accessory
            productService.addProduct(new Product("Apple AirPods Max", 519.0, "Silver", "Apple", cate_acces, 5, "The Apple AirPods Max is a line of wireless headphones designed, developed, marketed, and sold by Apple Inc. It is the first generation of the AirPods Max, succeeding the AirPods Pro and AirPods models. Apple CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2023. Pre-orders began on September 17, 2024, and the devices became available on September 24, 2024."));
            productService.addProduct(new Product("Apple AirPods Pro Gen 2 USB-C MagSafe Charge", 249.09, "White", "Apple", cate_acces, 5, "The Apple AirPods Pro Gen 2 USB-C MagSafe Charge is a line of wireless headphones designed, developed, marketed, and sold by Apple Inc. It is the second generation of the AirPods Pro, succeeding the AirPods Pro Gen 1 USB-C MagSafe Charge and AirPods Pro Gen 1 USB-C models. Apple CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2024. Pre-orders began on September 17, 2025, and the devices became available on September 24, 2025."));
            productService.addProduct(new Product("Apple AirPods 3 Lightning Charge", 168.68, "White", "Apple", cate_acces, 3, "The Apple AirPods 3 Lightning Charge is a line of wireless headphones designed, developed, marketed, and sold by Apple Inc. It is the third generation of the AirPods, succeeding the AirPods 2 Lightning Charge and AirPods 2 USB-C models. Apple CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2025. Pre-orders began on September 17, 2026, and the devices became available on September 24, 2026."));
            productService.addProduct(new Product("Apple Magic Keyboard with Touch ID", 154.49, "Silver", "Apple", cate_acces, 3, "The Apple Magic Keyboard with Touch ID is a line of wireless keyboards designed, developed, marketed, and sold by Apple Inc. It is the first generation of the Magic Keyboard with Touch ID, succeeding the Magic Keyboard and Magic Keyboard with Touch Bar models. Apple CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2026. Pre-orders began on September 17, 2027, and the devices became available on September 24, 2027."));
            productService.addProduct(new Product("Apple Pencil 2 MU8F2", 129.49, "White", "Apple", cate_acces, 3, "The Apple Pencil 2 MU8F2 is a line of stylus designed, and sold by Apple Inc. Specifically, it is designed for the iPad Pro 11 inch (3rd generation) and iPad Pro 12.9 inch (5th generation). It is the second generation of the Apple Pencil, succeeding the Apple Pencil 1st generation models."));
            productService.addProduct(new Product("Adapter Charging 85W Apple Macbook Pro MC556", 93.38, "White", "Apple", cate_acces, 3, "The Adapter Charging 85W Apple Macbook Pro MC556 is a line of wireless keyboards designed, developed, marketed, and sold by Apple Inc. It is the first generation of the Adapter Charging 85W Apple Macbook Pro MC556, succeeding the Adapter Charging 85W Apple Macbook Pro MC556 models. Apple CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2027. Pre-orders began on September 17, 2028, and the devices became available on September 24, 2028."));
            productService.addProduct(new Product("Apple MJ1L2 USB-C to VGA Multiport Converter Cable", 89.0, "White", "Apple", cate_acces, 3, "The Apple MJ1L2 USB-C to VGA Multiport Converter Cable is a line of wireless keyboards designed, developed, marketed, and sold by Apple Inc. It is the first generation of the Apple MJ1L2 USB-C to VGA Multiport Converter Cable, succeeding the Apple MJ1L2 USB-C to VGA Multiport Converter Cable models. Apple CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2028. Pre-orders began on September 17, 2029, and the devices became available on September 24, 2029."));
            productService.addProduct(new Product("Apple iPhone 15 Pro Max FineWoven Case with MagSafe", 62.69, "Green", "Apple", cate_acces, 3, "The Apple iPhone 15 Pro Max FineWoven Case with MagSafe is a line of phone case designed, and sold by Apple Inc. Specifically, it is designed for the iPhone 15 Pro Max. It is the first generation of the Apple iPhone 15 Pro Max FineWoven Case with MagSafe, succeeding the Apple iPhone 14 Pro Max FineWoven Case with MagSafe models."));
            productService.addProduct(new Product("Samsung Galaxy Buds 2 Pro R510N", 164.49, "Black", "Samsung", cate_acces, 5, "The Samsung Galaxy Buds 2 Pro R510N is a line of wireless headphones designed, developed, marketed, and sold by Samsung Inc. It is the second generation of the Galaxy Buds Pro, succeeding the Galaxy Buds Pro R500N and Galaxy Buds R500 models. Samsung CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2028. Pre-orders began on September 17, 2029, and the devices became available on September 24, 2029."));
            productService.addProduct(new Product("Samsung Galaxy Buds 2 R177N", 123.34, "White", "Samsung", cate_acces, 5, "The Samsung Galaxy Buds 3 R510N is a line of wireless headphones designed, developed, marketed, and sold by Samsung Inc. It is the third generation of the Galaxy Buds, succeeding the Galaxy Buds 2 R500N and Galaxy Buds R500 models. Samsung CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2029. Pre-orders began on September 17, 2030, and the devices became available on September 24, 2030."));
            productService.addProduct(new Product("Galaxy S23 Ultra Smart View Wallet Case", 49.49, "Black", "Samsung", cate_acces, 5, "The Galaxy S23 Ultra Smart View Wallet Case is a line of phone case designed, and sold by Samsung Inc. Specifically, it is designed for the Galaxy S23 Ultra. It is the first generation of the Galaxy S23 Ultra Smart View Wallet Case, succeeding the Galaxy S22 Ultra Smart View Wallet Case models."));
            productService.addProduct(new Product("Samsung 65W PD 3.0 Trio Power Adapter EP-T6530", 52.29, "Black", "Samsung", cate_acces, 5, "The Samsung 65W PD 3.0 Trio Power Adapter EP-T6530 is a line of charger designed, developed, marketed, and sold by Samsung Inc. It is the first generation of the Samsung 65W PD 3.0 Trio Power Adapter EP-T6530, succeeding the Samsung 65W PD 3.0 Trio Power Adapter EP-T6520 models."));
            productService.addProduct(new Product("Galaxy Z Flip5 Silicone Cover", 39.39, "Puple", "Samsung", cate_acces, 4, "The Galaxy Z Flip5 Silicone Cover is a line of phone case designed, and sold by Samsung Inc. Specifically, it is designed for the Galaxy Z Flip5. It is the first generation of the Galaxy Z Flip5 Silicone Cover, succeeding the Galaxy Z Flip4 Silicone Cover models."));
            productService.addProduct(new Product("Samsung 25W Battery Pack Type C EB-P5300", 51.8, "Black", "Samsung", cate_acces, 5, "The Samsung 25W Battery Pack Type C EB-P5300 is a line of battery pack designed, and sold by Samsung Inc. Specifically, it is designed for the Samsung Galaxy S23 Ultra. It is the first generation of the Samsung 25W Battery Pack Type C EB-P5300, succeeding the Samsung 25W Battery Pack Type C EB-P5200 models."));
            productService.addProduct(new Product("Samsung S Pen Pro EJ-P5450",  79.97, "Black", "Samsung", cate_acces, 3, "The Samsung S Pen Pro EJ-P5450 is a line of stylus designed, and sold by Samsung Inc. Specifically, it is designed for the Samsung Galaxy S23 Ultra. It is the first generation of the Samsung S Pen Pro EJ-P5450, succeeding the Samsung S Pen Pro EJ-P5350 models."));
            productService.addProduct(new Product("OPPO ENCO Air 2 Pro ETE21", 65.56, "White", "OPPO", cate_acces, 5, "The OPPO ENCO Air 2 Pro ETE21 is a line of wireless headphones designed, developed, marketed, and sold by OPPO Inc. It is the second generation of the ENCO Air 2 Pro, succeeding the ENCO Air 2 Pro ETE20 and ENCO Air 2 ETE20 models. OPPO CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2029. Pre-orders began on September 17, 2030, and the devices became available on September 24, 2030."));
            productService.addProduct(new Product("OPPO MH151", 15.0, "Black", "OPPO", cate_acces, 5, "The OPPO MH151 is a line of wireless headphones designed, developed, marketed, and sold by OPPO Inc. It is the first generation of the MH151, succeeding the MH150 models. OPPO CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2030. Pre-orders began on September 17, 2031, and the devices became available on September 24, 2031."));
            productService.addProduct(new Product("Cable Type C SuperVOOC 1m OPPO DL129", 8.66, "White", "OPPO", cate_acces, 5, "The Cable Type C SuperVOOC 1m OPPO DL129 is a line of cable designed, developed, marketed, and sold by OPPO Inc. It is the first generation of the Cable Type C SuperVOOC 1m OPPO DL129, succeeding the Cable Type C SuperVOOC 1m OPPO DL128 models. OPPO CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2031. Pre-orders began on September 17, 2032, and the devices became available on September 24, 2032."));
            productService.addProduct(new Product("Baseus IOTA 450W Portable Power Station 90000mAh", 272.89, "Green", "Baseus", cate_acces, 5, "The Baseus IOTA 450W Portable Power Station 90000mAh is a line of battery pack designed, developed, marketed, and sold by Baseus Inc. It is the first generation of the Baseus IOTA 450W Portable Power Station 90000mAh, succeeding the Baseus IOTA 450W Portable Power Station 80000mAh models. Baseus CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2032. Pre-orders began on September 17, 2033, and the devices became available on September 24, 2033."));
            productService.addProduct(new Product("Baseus 22.5W Battery Charger Powerbank 20000mAh", 29.99, "White", "Baseus", cate_acces, 5, "The Baseus 65W GaN2 Pro Quick Charger 3C1A is a line of charger designed, developed, marketed, and sold by Baseus Inc. It is the first generation of the Baseus 65W GaN2 Pro Quick Charger 3C1A, succeeding the Baseus 65W GaN2 Pro Quick Charger 2C2A models. Baseus CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2033. Pre-orders began on September 17, 2034, and the devices became available on September 24, 2034."));
            productService.addProduct(new Product("Baseus Bowie M2s True Wireless Earphones", 39.69, "White", "Baseus", cate_acces, 5, "The Baseus Bowie M2s True Wireless Earphones is a line of wireless headphones designed, developed, marketed, and sold by Baseus Inc. It is the second generation of the Baseus Bowie M2s, succeeding the Baseus Bowie M2 models. Baseus CEO Tim Cook unveiled the devices alongside a new iPad and Apple Watch during a virtual press event on September 14, 2034. Pre-orders began on September 17, 2035, and the devices became available on September 24, 2035."));
            System.out.println("The application has been initialized successfully!");
    }
}
